In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pandas as pd
import numpy as np
import pickle

In [5]:
#load files
model=load_model('model.h5')

with open('OneHotGeo.pkl','rb') as f:
    encoded_geo=pickle.load(f)

with open('lblEncoderGender.pkl','rb') as f:
    encoded_gender=pickle.load(f)

with open('scaler.pkl','rb') as f:
    scaler=pickle.load(f)

In [9]:
df=pd.read_csv('Churn_Modelling.csv')
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [46]:
input_data={
    'CreditScore':510,
    'Geography':'France',
    'Gender':'Male', 
    'Age':24, 
    'Tenure':3, 
    'Balance':60000, 
    'NumOfProducts':2, 
    'HasCrCard':1,
    'IsActiveMember':1, 
    'EstimatedSalary':50000, 
}

In [47]:
encoded_geo.transform([[input_data['Geography']]])

c:\ML Project Udemy\Ann_Classification\venv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0.]])

In [48]:
geo_encoded=encoded_geo.transform([[input_data['Geography']]])

c:\ML Project Udemy\Ann_Classification\venv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [49]:
geo_encoded_df=pd.DataFrame(geo_encoded,columns=encoded_geo.get_feature_names_out(['Geography'])) #encoded_geo.get_feature_names_out(['Geography'])

In [50]:
geo_encoded_df

Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [51]:
pd.DataFrame([input_data])

CreditScore Geography Gender  Age  Tenure  Balance  NumOfProducts  \
0          510    France   Male   24       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

In [52]:
pd.DataFrame([input_data]).reset_index(drop=True)

CreditScore Geography Gender  Age  Tenure  Balance  NumOfProducts  \
0          510    France   Male   24       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

array([1])

In [57]:
input_data_df=pd.concat([pd.DataFrame([input_data]),geo_encoded_df],axis=1)

In [61]:
input_data_df

CreditScore Geography Gender  Age  Tenure  Balance  NumOfProducts  \
0          510    France   Male   24       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  Geography_France  \
0          1               1            50000               1.0   

   Geography_Germany  Geography_Spain  
0                0.0              0.0

In [56]:
pd.DataFrame([input_data])

CreditScore Geography Gender  Age  Tenure  Balance  NumOfProducts  \
0          510    France   Male   24       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

In [71]:
input_data_df['Gender']=encoded_gender.transform(input_data_df['Gender'])


In [74]:
input_data_df.drop(columns=['Geography'],axis=True,inplace=True)

In [75]:
input_data_df

CreditScore  Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0          510       1   24       3    60000              2          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1            50000               1.0                0.0   

   Geography_Spain  
0              0.0

In [77]:
# Scaling the data
input_data_df=scaler.transform(input_data_df)

In [78]:
input_data_df

array([[-1.45183216,  0.91000202, -1.41243731, -0.70004869, -0.25251804,
         0.80397132,  0.65581709,  0.98195385, -0.87586981,  0.98724551,
        -0.57780985, -0.56700883]])

In [80]:
prediction=model.predict(input_data_df)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step


In [81]:
prediction[0][0]

0.018879766

In [83]:

input_data=pd.DataFrame({
    'CreditScore':[4] ,
    # 'Geography': encoded_geo.transform([geography])[0],
    'Gender': encoded_gender.transform(['Male']),
    'Age': [22],
    'Tenure': [2],
    'Balance':[3333],
    'NumOfProducts': [1],
    'HasCrCard':[1],
    'IsActiveMember': [1],
    'EstimatedSalary': [1],
    })


encoded_geo_val=encoded_geo.transform([['France']])

# geo_encoded_df=pd.DataFrame(encoded_geo_val,columns=encoded_geo.get_feature_names_out([geography]))
# input_data_df=pd.concat([input_data,geo_encoded_df],axis=1)

c:\ML Project Udemy\Ann_Classification\venv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [85]:
encoded_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [88]:
encoded_geo.categories_[0]

array(['France', 'Germany', 'Spain'], dtype=object)

In [89]:
encoded_geo.categories_

[array(['France', 'Germany', 'Spain'], dtype=object)]